ci/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^list/$', views.List.as_view(), name='list'),
    url(r'^add/$', views.Create.as_view(), name='add'),
    url(r'^delete/(?P<pk>[\d]+)/$', views.Delete.as_view(), name='delete'),
]

slothmin/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('administration:actions'), permanent=True), name='go_main'),
    url(r'^servers/', include('servers.urls', namespace='servers', app_name='servers')),
    url(r'^administration/', include('administration.urls', namespace='administration', app_name='administration')),
    url(r'^ci/', include('ci.urls', namespace='ci', app_name='ci')),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'simple_form.html'},
        name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': "login"}, name="logout"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>slothmin || {{ title }}</title>

  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'growl/jquery.growl.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}"/>
  {% if additional_css %}
    {% for css in additional_css %}
      <link rel="stylesheet" type="text/css" href="{{ css }}"/>
    {% endfor %}
  {% endif %}

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'growl/jquery.growl.js' %}"></script>
  <script src="{% static 'js/endless-pagination.js' %}"></script>
  <script src="{% static 'js/endless_on_scroll.js' %}"></script>
  {% bootstrap_javascript %}
  <script src="{% static 'js/system_ws.js' %}"></script>
  <script src="{% static 'js/js.js' %}"></script>
  {% if additional_scripts %}
    {% for script_name in additional_scripts %}
      <script src="{{ script_name }}"></script>
    {% endfor %}
  {% endif %}
</head>
<script>system_ws = SystemWS("{{ system_ws_url|safe }}");</script>

<body>
  <div class="container">
    {% if request.user.is_authenticated %}
      {% include 'header.html' %}
    {% endif %}
    {% block content %}{% endblock %}
  </div>
</body>

templates/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Сервера<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'servers:add' %}">Добавить сервер</a></li>
              <li><a href="{% url 'servers:list' %}">Список серверов</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Администрирование<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'administration:actions' %}">Действия</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">continuous integration<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'ci:list' %}">Список коммит чекеров</a></li>
              <li><a href="{% url 'ci:add' %}">Добавить коммит чекер</a></li>
            </ul>
          </li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'logout' %}">Выйти</a>
          </li>
        </ul>
    </div>
</nav>